[theme]
base = "dark"

# General color setup
textColor = "#ffffff"
primaryColor = "#008024"
backgroundColor = "#11102d"
secondaryBackgroundColor = "#2a2f3d"

# Widgets
showWidgetBorder = true
borderColor = "#314158"

# Dataframes
dataframeHeaderBackgroundColor = "#000000"

# Base text
font = "'Special Gothic Expanded One':https://fonts.googleapis.com/css2?family=Special+Gothic+Expanded+One&display=swap"
baseFontWeight = 300
baseFontSize = 14

# Heading text
headingFont = "Space Grotesk"
headingFontWeights = [500, 500, 500, 500, 500, 500]
headingFontSizes = ["5rem", "3rem", "3rem"]