[theme]
base = "dark"

# General color setup
textColor = "#e2e8f0"
primaryColor = "#615fff"
backgroundColor = "#1d293d"
secondaryBackgroundColor = "#0f172b"

# Widgets
showWidgetBorder = true
borderColor = "#314158"

# Dataframes
dataframeHeaderBackgroundColor = "#1d293d"

# Base text
font = "'Special Gothic Expanded One':https://fonts.googleapis.com/css2?family=Special+Gothic+Expanded+One&display=swap"
baseFontWeight = 300
baseFontSize = 14

# Heading text
headingFont = "Space Grotesk"
headingFontWeights = [500, 500, 500, 500, 500, 500]
headingFontSizes = ["3rem", "3rem", "3rem"]